### PR TITLE
Create Subnets class for classic infrastructures

### PR DESCRIPTION
**Pull request by mor120**

### CODE REVIEW

**Comment by goldyfruit** [comment]
Hey @mor12, let me know when the PR is not in WIP anymore!
Thanks :+1:

**Comment by mor120** [comment]
Hey @goldyfruit 
From my side, it's not anymore on WIP and I think it's ready to be merged.
Thanks.

**Comment by mor120** [comment]
> Thanks for the PR @mor120
No problem :)
BTW, when are you expected to create a new release?

**Comment by goldyfruit** [comment]
> > Thanks for the PR @mor120
> 
> No problem :) BTW, when are you expected to create a new release?

Just created release 1.1.0 and published on PyPi.

**Pull request merged**
